In [1]:
from sktime.forecasting.theta import ThetaForecaster
from sktime.performance_metrics.forecasting.probabilistic import PinballLoss

c:\users\e.enticott\repositories\sktime\sktime\sktime\utils\validation\series.py:21: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  VALID_INDEX_TYPES = (pd.Int64Index, pd.RangeIndex, pd.PeriodIndex, pd.DatetimeIndex)
c:\users\e.enticott\repositories\sktime\sktime\sktime\forecasting\base\_fh.py:18: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  RELATIVE_TYPES = (pd.Int64Index, pd.RangeIndex)
c:\users\e.enticott\repositories\sktime\sktime\sktime\forecasting\base\_fh.py:19: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  ABSOLUTE_TYPES = (pd.Int64Index, pd.RangeIndex, pd.DatetimeIndex, pd.PeriodIndex)
c:\users\e.enticott\repositories\sktime\sktime\sktime\datatypes\_series

In [2]:
import numpy as np

from sktime.datasets import load_airline
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.tests._config import TEST_OOS_FHS
from sktime.forecasting.theta import ThetaForecaster
from sktime.utils.validation.forecasting import check_fh

y = np.log1p(load_airline())
y_train, y_test = temporal_train_test_split(y)
fh = np.arange(len(y_test)) + 1

f = ThetaForecaster(sp=12)
f.fit(y_train)
y_pred = f.predict(fh=fh)

np.testing.assert_allclose(y_pred, y_test, rtol=0.05)

c:\users\e.enticott\repositories\sktime\sktime\sktime\forecasting\tests\_config.py:85: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  "int": pd.Int64Index,
c:\users\e.enticott\repositories\sktime\sktime\sktime\datasets\_single_problem_loaders.py:658: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  y = pd.read_csv(path, index_col=0, squeeze=True, dtype={1: float})
c:\users\e.enticott\repositories\sktime\sktime\sktime\forecasting\base\adapters\_statsmodels.py:50: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  if isinstance(y, pd.Series) and type(y.index) == pd.Int64Index:
c:\users\e.enticott\repositories\sktime\sktime\sktime\forecasting\base\_fh.py:100: FutureWarning: panda

In [3]:
dat = f.predict_quantiles(fh, alpha=[0.2, 0.5, 0.8])
dat

c:\users\e.enticott\repositories\sktime\sktime\sktime\forecasting\base\_fh.py:100: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  values = pd.Int64Index(values, dtype=int)
c:\users\e.enticott\repositories\sktime\sktime\sktime\utils\datetime.py:40: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  return pd.Int64Index([d.n / count for d in duration])


Quantiles                    
              0.2       0.5       0.8
1958-01  5.808697  5.847790  5.886884
1958-02  5.794612  5.841117  5.887623
1958-03  5.945330  5.998219  6.051108
1958-04  5.895514  5.954095  6.012675
1958-05  5.886980  5.950747  6.014513
1958-06  6.019139  6.087700  6.156261
1958-07  6.119070  6.192112  6.265153
1958-08  6.107002  6.184265  6.261527
1958-09  5.974790  6.056055  6.137320
1958-10  5.819171  5.904250  5.989329
1958-11  5.663438  5.752167  5.840896
1958-12  5.805605  5.897841  5.990076
1959-01  5.817520  5.913132  6.008745
1959-02  5.807449  5.906324  6.005199
1959-03  5.963084  6.065117  6.167150
1959-04  5.915343  6.020439  6.125535
1959-05  5.908920  6.016992  6.125065
1959-06  6.044438  6.155407  6.266376
1959-07  6.147125  6.260917  6.374709
1959-08  6.136373  6.252919  6.369465
1959-09  6.003987  6.123224  6.242461
1959-10  5.847806  5.969675  6.091543
1959-11  5.691403  5.815847  5.940292
1959-12  5.836106  5.963074  6.090042
1960-01  5.849032  5.978474  6.107917
1960-02  5.839660  5.971531  6.103401
1960-03  5.997761  6.132015  6.266270
1960-04  5.950187  6.086783  6.223380
1960-05  5.944338  6.083238  6.222138
1960-06  6.081949  6.223114  6.364280
1960-07  6.186327  6.329722  6.473116
1960-08  6.175983  6.321573  6.467163
1960-09  6.042640  6.190393  6.338146
1960-10  5.885215  6.035099  6.184984
1960-11  5.727541  5.879528  6.031514
1960-12  5.874247  6.028307  6.182366

In [4]:
y_test

Period
1958-01    5.831882
1958-02    5.765191
1958-03    5.894403
1958-04    5.855072
1958-05    5.897154
1958-06    6.077642
1958-07    6.198479
1958-08    6.226537
1958-09    6.003887
1958-10    5.886104
1958-11    5.739793
1958-12    5.823046
1959-01    5.888878
1959-02    5.837730
1959-03    6.008813
1959-04    5.983936
1959-05    6.042633
1959-06    6.159095
1959-07    6.308098
1959-08    6.327937
1959-09    6.139885
1959-10    6.011267
1959-11    5.894403
1959-12    6.006353
1960-01    6.035481
1960-02    5.971262
1960-03    6.040255
1960-04    6.135565
1960-05    6.159095
1960-06    6.284134
1960-07    6.434547
1960-08    6.408529
1960-09    6.232448
1960-10    6.135565
1960-11    5.968708
1960-12    6.070738
Freq: M, Name: Number of airline passengers, dtype: float64

In [5]:
loss = PinballLoss(alphas=[0.2, 0.5, 0.8])
loss

PinballLoss(alphas=array([0.2, 0.5, 0.8]))

In [22]:
import pandas as pd

pd.DataFrame([[1, 1, 1]], columns=[1, 1, 1]).shape

(1, 3)

In [21]:
np.isclose(pd.DataFrame([0]), 0)

array([[ True]])

In [7]:
loss._evaluate_by_index

<bound method PinballLoss._evaluate_by_index of PinballLoss(alphas=array([0.2, 0.5, 0.8]))>

In [8]:
loss._evaluate_by_index(y_test, y_pred, 0.4, "uniform_average").to_numpy()

array([0.00954479, 0.04555572, 0.06228963, 0.05941362, 0.03215572,
       0.00603449, 0.00254673, 0.0169088 , 0.03130099, 0.01088778,
       0.00742446, 0.04487681, 0.01455265, 0.04115609, 0.03378233,
       0.02190165, 0.0102562 , 0.00147531, 0.01887267, 0.03000721,
       0.0066642 , 0.01663693, 0.03142214, 0.01731183, 0.02280286,
       0.00016123, 0.05505632, 0.01951259, 0.03034299, 0.02440787,
       0.04192995, 0.03478237, 0.01682212, 0.04018622, 0.03567184,
       0.01697246])

In [9]:
dat.index

PeriodIndex(['1958-01', '1958-02', '1958-03', '1958-04', '1958-05', '1958-06',
             '1958-07', '1958-08', '1958-09', '1958-10', '1958-11', '1958-12',
             '1959-01', '1959-02', '1959-03', '1959-04', '1959-05', '1959-06',
             '1959-07', '1959-08', '1959-09', '1959-10', '1959-11', '1959-12',
             '1960-01', '1960-02', '1960-03', '1960-04', '1960-05', '1960-06',
             '1960-07', '1960-08', '1960-09', '1960-10', '1960-11', '1960-12'],
            dtype='period[M]')

In [25]:
ltest_df = loss.evaluate_by_index(y_test, dat)

In [41]:
[a for a in ltest_df.values[:, 0]]

[0.004637141365195419,
 0.023536446471495512,
 0.04074174287685182,
 0.032353650794869536,
 0.0020346994807507457,
 0.011700698965443302,
 0.015881672307354044,
 0.023906941328276334,
 0.0058193165703039895,
 0.013386543954386987,
 0.015271050808461695,
 0.0034881304841698937,
 0.014271685978815719,
 0.006056311199774989,
 0.009145822630155643,
 0.01371867122829702,
 0.02674258727899357,
 0.02293144631983797,
 0.032194687186404634,
 0.03831284893870031,
 0.027179518793080427,
 0.0326921739714507,
 0.04059993992241076,
 0.03404950255659252,
 0.03728989469829074,
 0.026320313304665534,
 0.008498763331017933,
 0.0370756559034426,
 0.04295145220664179,
 0.04043697125811274,
 0.04964393190187355,
 0.04650923418268427,
 0.037961683961841075,
 0.050070060488346974,
 0.048233219136790954,
 0.03929814586015201]

In [11]:
alpha = np.array([0.8, 0.5, 0.2])

In [12]:
diff = dat.to_numpy().T - y_test.to_numpy()
diff

array([[-0.02318571,  0.02942056,  0.05092718,  0.04044206, -0.0101735 ,
        -0.05850349, -0.07940836, -0.11953471, -0.02909658, -0.06693272,
        -0.07635525, -0.01744065, -0.07135843, -0.03028156, -0.04572911,
        -0.06859336, -0.13371294, -0.11465723, -0.16097344, -0.19156424,
        -0.13589759, -0.16346087, -0.2029997 , -0.17024751, -0.18644947,
        -0.13160157, -0.04249382, -0.18537828, -0.21475726, -0.20218486,
        -0.24821966, -0.23254617, -0.18980842, -0.2503503 , -0.2411661 ,
        -0.19649073],
       [ 0.01590798,  0.0759262 ,  0.10381605,  0.0990227 ,  0.05359287,
         0.01005749, -0.00636682, -0.04227201,  0.05216831,  0.01814631,
         0.01237411,  0.07479469,  0.02425441,  0.06859349,  0.05630388,
         0.03650275, -0.02564051, -0.00368829, -0.04718167, -0.07501802,
        -0.01666051, -0.04159233, -0.07855534, -0.04327958, -0.05700715,
         0.00026872,  0.09176054, -0.04878147, -0.07585748, -0.06101968,
        -0.10482487, -0.08695

In [13]:
sign = (diff >= 0).astype(diff.dtype)
np.average((((sign * diff).T * alpha) - (((1 - sign) * diff).T * (1 - alpha))), axis=0)
# np.mean((((sign * diff).T * alpha).T - ((1-alpha) * ((1-sign) * diff).T))[2])

array([0.02652618, 0.02614339, 0.01988932])

In [14]:
import pandas as pd

out_df = pd.DataFrame([[5, 7, 4]], columns=[0.1, 0.2, 0.3])

In [15]:
for i, j in enumerate([0.2, 0.3]):
    print(i, j)

0 0.2
1 0.3


In [16]:
np.full([2, 5], None)

array([[None, None, None, None, None],
       [None, None, None, None, None]], dtype=object)

In [17]:
(1 - alpha) * ((1 - sign) * diff).T

array([[-0.00463714,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-0.0020347 ,  0.        ,  0.        ],
       [-0.0117007 ,  0.        ,  0.        ],
       [-0.01588167, -0.00318341,  0.        ],
       [-0.02390694, -0.021136  ,  0.        ],
       [-0.00581932,  0.        ,  0.        ],
       [-0.01338654,  0.        ,  0.        ],
       [-0.01527105,  0.        ,  0.        ],
       [-0.00348813,  0.        ,  0.        ],
       [-0.01427169,  0.        ,  0.        ],
       [-0.00605631,  0.        ,  0.        ],
       [-0.00914582,  0.        ,  0.        ],
       [-0.01371867,  0.        ,  0.        ],
       [-0.02674259, -0.01282026,  0.        ],
       [-0.02293145, -0.00184414,  0.        ],
       [-0.03219469, -0.02359084,  0.        ],
       [-0.03831285, -0.03750901,  0.        ],
       [-0.02717952, -0.00833026,  0.   

In [18]:
# diff = y_test - y_pred
sign = (diff >= 0).astype(diff.dtype)
loss = alpha * sign * diff - (1 - alpha) * (1 - sign) * diff
loss

ValueError: operands could not be broadcast together with shapes (3,) (3,36) 

In [ ]:
y_true = dat["Quantiles"][0.5]

In [ ]:
loss.evaluate(y_true, y_pred)

0.0

In [ ]:
QUANTILE_PRED = f.predict_quantiles(fh=fh, alpha=[0.05, 0.5, 0.95])

c:\users\e.enticott\repositories\sktime\sktime\sktime\forecasting\base\_fh.py:100: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  values = pd.Int64Index(values, dtype=int)
c:\users\e.enticott\repositories\sktime\sktime\sktime\utils\datetime.py:40: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  return pd.Int64Index([d.n / count for d in duration])


In [ ]:
loss(y_true, QUANTILE_PRED)

0.0

In [ ]:
loss.evaluate_by_index(y_true, y_pred)
assert (a == 0 for a in loss.evaluate_by_index(y_true, y_pred))

c:\users\e.enticott\repositories\sktime\sktime\sktime\performance_metrics\forecasting\probabilistic\_classes.py:74: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  out_series = pd.Series(index=pd.RangeIndex(0, n))
c:\users\e.enticott\repositories\sktime\sktime\sktime\performance_metrics\forecasting\probabilistic\_classes.py:74: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  out_series = pd.Series(index=pd.RangeIndex(0, n))


In [ ]:
f.predict_interval(fh)

Coverage          
              0.9          
            lower     upper
1958-01  5.771386  5.924195
1958-02  5.750227  5.932007
1958-03  5.894854  6.101584
1958-04  5.839605  6.068584
1958-05  5.826123  6.075371
1958-06  5.953705  6.221694
1958-07  6.049360  6.334863
1958-08  6.033263  6.335266
1958-09  5.897232  6.214878
1958-10  5.737973  6.070528
1958-11  5.578756  5.925579
1958-12  5.717577  6.078104
1959-01  5.726268  6.099997
1959-02  5.713084  6.099564
1959-03  5.865705  6.264529
1959-04  5.815041  6.225837
1959-05  5.805777  6.228208
1959-06  5.938531  6.372283
1959-07  6.038524  6.483310
1959-08  6.025142  6.480695
1959-09  5.890189  6.356259
1959-10  5.731497  6.207853
1959-11  5.572635  6.059060
1959-12  5.714929  6.211218
1960-01  5.725494  6.231455
1960-02  5.713805  6.229256
1960-03  5.869630  6.394400
1960-04  5.819820  6.353746
1960-05  5.811774  6.354702
1960-06  5.947223  6.499006
1960-07  6.049473  6.609971
1960-08  6.037033  6.606113
1960-09  5.901626  6.479159
1960-10  5.742167  6.328032
1960-11  5.582488  6.176568
1960-12  5.727215  6.329399

In [ ]:
test_loss = PinballLoss(alpha=0.5)