# Early time series classification with sktime

Early time series classification (eTSC) is the problem of classifying a time series after as few measurements as possible with the highest possible accuracy. The most critical issue of any eTSC method is to decide when enough data of a time series has been seen to take a decision: Waiting for more data points usually makes the classification problem easier but delays the time in which a classification is made; in contrast, earlier classification has to cope with less input data, often leading to inferior accuracy.

This notebook gives a quick guide to get you started with running eTSC algorithms in sktime.


#### References:

\[1\] Schäfer, P., & Leser, U. (2020). TEASER: early and accurate time series classification. Data mining and knowledge discovery, 34(5), 1336-1362

## Data sets and problem types
The UCR/UEA [time series classification archive](https://timeseriesclassification.com/) contains a large number of example TSC problems that have been used thousands of times in the literature to assess TSC algorithms. Read the data loading documentation and notebooks for details on the sktime data formats and loading data for sktime.

In [107]:
# Imports used in this notebook
import numpy as np

from sktime.classification.early_classification._teaser import TEASER
from sktime.classification.interval_based import TimeSeriesForestClassifier
from sktime.datasets import load_arrow_head

In [108]:
# Load default train/test splits from sktime/datasets/data
arrow_train_X, arrow_train_y = load_arrow_head(split="train", return_type="numpy3d")
arrow_test_X, arrow_test_y = load_arrow_head(split="test", return_type="numpy3d")

arrow_test_X.shape

(175, 1, 251)

## Building the TEASER classifier

TEASER \[1\] is a two-tier model using a base classifier to make predictions and a decision making estimator to decide whether these predictions are safe. As a first tier, TEASER requires a TSC algorithm, such as WEASEL, which produces class probabilities as output. As a second tier an anomaly detector is required, such as a one-class SVM.

In [109]:
teaser = TEASER(
    random_state=0,
    classification_points=[25, 50, 75, 100, 125, 150, 175, 200, 251],
    estimator=TimeSeriesForestClassifier(n_estimators=10, random_state=0),
)
teaser.fit(arrow_train_X, arrow_train_y)

TEASER(classification_points=[25, 50, 75, 100, 125, 150, 175, 200, 251],
       estimator=TimeSeriesForestClassifier(n_estimators=10, random_state=0),
       random_state=0)

## Determine the accuracy and earliness on the test data

Commonly accuracy is used to determine the correctness of the predictions, while earliness is used to determine how much of the series is required on average to obtain said accuracy. I.e. for the below values, using just 43% of the full test data, we were able to get an accuracy of 69%.

In [110]:
hm, acc, earl = teaser.score(arrow_test_X, arrow_test_y)

In [111]:
print("Earliness on Test Data %2.2f" % earl)
print("Accuracy on Test Data %2.2f" % acc)
print("Harmonic Mean on Test Data %2.2f" % hm)

Earliness on Test Data 0.43
Accuracy on Test Data 0.69
Harmonic Mean on Test Data 0.62


### Determine the accuracy and earliness on the train data

In [112]:
print("Earliness on Train Data %2.2f" % teaser._train_earliness)
print("Accuracy on Train Data %2.2f" % teaser._train_accuracy)

Earliness on Train Data 0.36
Accuracy on Train Data 0.78


### Comparison to Classification on full Test Data

With the full test data, we would obtain 68% accuracy with the same classifier.

In [113]:
accuracy = (
    TimeSeriesForestClassifier(n_estimators=10, random_state=0)
    .fit(arrow_train_X, arrow_train_y)
    .score(arrow_test_X, arrow_test_y)
)
print("Accuracy on the full Test Data %2.2f" % accuracy)

Accuracy on the full Test Data 0.68


## Classifying with incomplete time series

The main draw of eTSC is the capabilility to make classifications with incomplete time series. sktime eTSC algorithms accept inputs with less time points than the full series length, and output three items: The prediction made, whether the algorithm thinks the prediction is safe and information about the decision such as the time stamp it was made at (sometimes used as an input to provide the algorithm with information from previous decisions).

### First test with only 50 datapoints (out of 251)

In [256]:
X = arrow_test_X[:, :, :50]
probas, decisions, _ = teaser.predict_proba(X)
idx = (probas >= 0).all(axis=1)
print("First 10 Finished prediction\n", np.argwhere(idx).flatten()[:10])
print("First 10 Probabilities of finished predictions\n", probas[idx][:10])

First 10 Finished prediction
 [ 2  5 15 21 30 45 47 56 61 63]
First 10 Probabilities of finished predictions
 [[0.2 0.3 0.5]
 [0.7 0.2 0.1]
 [0.1 0.  0.9]
 [0.2 0.2 0.6]
 [0.7 0.1 0.2]
 [0.1 0.6 0.3]
 [0.3 0.2 0.5]
 [0.8 0.  0.2]
 [0.9 0.1 0. ]
 [0.9 0.  0.1]]


In [257]:
_, acc, _ = teaser.score(X, arrow_test_y)
print("Accuracy with 50 points on Test Data %2.2f" % acc)

Accuracy with 50 points on Test Data 0.65


### We may also do predictions in a streaming scenario where more data becomes available from time to time

The rationale is to keep the state info from the previous predictions and pass there to TEASER whenever new data is available.

In [255]:
test_points = [50, 75, 100, 125, 150, 175, 200, 251]
final_probas = np.zeros((arrow_test_X.shape[0], np.unique(arrow_test_y).shape[0]))
final_decisions = np.zeros(arrow_test_X.shape[0])

states = None
for i in test_points:
    X = arrow_test_X[:, :, :i]
    probas, decisions, states = teaser.predict_proba(X, state_info=states)

    for n in range(arrow_test_X.shape[0]):
        if decisions[n] and final_decisions[n] == 0:
            final_probas[n] = probas[n]
            final_decisions[n] = i

    final_hm, final_earliness, final_acc = teaser._compute_harmonic_mean(
        X.shape[2], states, arrow_test_y
    )

    print("Earliness on length %2f is %2.2f" % (i, final_earliness))
    print("Accuracy on length %2f is %2.2f" % (i, final_acc))
    print("Harmonic Mean on length %2f is %2.2f" % (i, final_hm))

    print("...........")

print("Time Stamp of final decisions", final_decisions)

Earliness on length 50.000000 is 0.65
Accuracy on length 50.000000 is 1.00
Harmonic Mean on length 50.000000 is 0.00
...........
Earliness on length 75.000000 is 0.63
Accuracy on length 75.000000 is 0.92
Harmonic Mean on length 75.000000 is 0.14
...........
Earliness on length 100.000000 is 0.63
Accuracy on length 100.000000 is 0.80
Harmonic Mean on length 100.000000 is 0.30
...........
Earliness on length 125.000000 is 0.66
Accuracy on length 125.000000 is 0.72
Harmonic Mean on length 125.000000 is 0.39
...........
Earliness on length 150.000000 is 0.66
Accuracy on length 150.000000 is 0.64
Harmonic Mean on length 150.000000 is 0.46
...........
Earliness on length 175.000000 is 0.69
Accuracy on length 175.000000 is 0.57
Harmonic Mean on length 175.000000 is 0.53
...........
Earliness on length 200.000000 is 0.66
Accuracy on length 200.000000 is 0.52
Harmonic Mean on length 200.000000 is 0.56
...........
Earliness on length 251.000000 is 0.69
Accuracy on length 251.000000 is 0.43
Harmo